# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install X11 dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libxrandr-dev libxi-dev xorg-dev
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v ./... -covermode=count -coverprofile=coverage.out
        go tool cover -func=coverage.out -o=coverage.out
    
    - name: Update coverage report
      #if: ${{ github.ref == 'refs/heads/master' }}
      uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: coverage.out
        report: true
        chart: true
        amend: true
